name: CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Run build
        run: |
          yarn install --frozen-lockfile
          yarn build
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Run lints
        run: |
          yarn install --frozen-lockfile
          yarn lint
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js

        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Run test
        run: |
          yarn install --frozen-lockfile
          yarn test

  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js

        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Run test:coverage
        run: |
          yarn install --frozen-lockfile
          yarn test:coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
